--- #YAML:1.0
name:               DBIx-Report-Excel
version:            0.2a
abstract:           creating Excel reports from SQL statements
author:
    - Dmytro Kovalov <dmytro.kovalov@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Tabular::Dumper:  0.06
    Data::Tabular::Dumper::Excel:  0
    Spreadsheet::WriteExcel:  0
    SQL::Parser:          1.16
    SQL::Script:          1.05
    YAML:                 0.68
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
